# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170803_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=300),
        ),
    ]
