# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170803_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='from_email',
            new_name='email',
        ),
    ]
