# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170803_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
